name: linting + remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: PHP Lint
      uses: michaelw90/PHP-Lint@1.0.0

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ssh.roomhub.ga
        username: roomhub
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd public_html
          git pull
          composer install
          php migrate.php
          sudo rm /tmp/twig/cache -rf

